// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseAndImport(arg1:string):Promise<main.ImportResponse>;

export function DeleteDocument(arg1:string):Promise<Array<main.Document>>;

export function DeleteDocuments(arg1:Array<string>):Promise<Array<main.Document>>;

export function ExportCSV():Promise<main.ExportResponse>;

export function GetCompatibility():Promise<main.CompatibilityReport>;

export function GetDaemonLogs():Promise<string>;

export function GetModelStatus():Promise<main.ModelStatus>;

export function GetProcessingStatus():Promise<main.ProcessingStatus>;

export function ImportDroppedFiles(arg1:Array<string>,arg2:string):Promise<main.ImportResponse>;

export function ListDocuments():Promise<Array<main.Document>>;

export function ListFields():Promise<Array<main.TemplateField>>;

export function OpenDocumentFile(arg1:string):Promise<string>;

export function ReprocessDocuments(arg1:Array<string>,arg2:string):Promise<main.ImportResponse>;

export function SaveField(arg1:main.TemplateField):Promise<Array<main.TemplateField>>;

export function SetFieldVisibility(arg1:string,arg2:boolean):Promise<Array<main.TemplateField>>;

export function SetModelMode(arg1:string):Promise<main.ModelStatus>;

export function SetStatus(arg1:string,arg2:string):Promise<Array<main.Document>>;

export function UpdateFieldValue(arg1:string,arg2:string,arg3:string):Promise<Array<main.Document>>;
