// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseAndImport(arg1) {
  return window['go']['main']['App']['ChooseAndImport'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteDocuments(arg1) {
  return window['go']['main']['App']['DeleteDocuments'](arg1);
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function GetCompatibility() {
  return window['go']['main']['App']['GetCompatibility']();
}

export function GetDaemonLogs() {
  return window['go']['main']['App']['GetDaemonLogs']();
}

export function GetModelStatus() {
  return window['go']['main']['App']['GetModelStatus']();
}

export function GetProcessingStatus() {
  return window['go']['main']['App']['GetProcessingStatus']();
}

export function ImportDroppedFiles(arg1, arg2) {
  return window['go']['main']['App']['ImportDroppedFiles'](arg1, arg2);
}

export function ListDocuments() {
  return window['go']['main']['App']['ListDocuments']();
}

export function ListFields() {
  return window['go']['main']['App']['ListFields']();
}

export function OpenDocumentFile(arg1) {
  return window['go']['main']['App']['OpenDocumentFile'](arg1);
}

export function ReprocessDocuments(arg1, arg2) {
  return window['go']['main']['App']['ReprocessDocuments'](arg1, arg2);
}

export function SaveField(arg1) {
  return window['go']['main']['App']['SaveField'](arg1);
}

export function SetFieldVisibility(arg1, arg2) {
  return window['go']['main']['App']['SetFieldVisibility'](arg1, arg2);
}

export function SetModelMode(arg1) {
  return window['go']['main']['App']['SetModelMode'](arg1);
}

export function SetStatus(arg1, arg2) {
  return window['go']['main']['App']['SetStatus'](arg1, arg2);
}

export function UpdateFieldValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateFieldValue'](arg1, arg2, arg3);
}
